С помощью массивов numpy создайте таблицу умножения.

In [ ]:
import numpy as np

n = 10
table = np.arange(1, n+1)
print(np.outer(table, table))

[[  1   2   3   4   5   6   7   8   9  10]
 [  2   4   6   8  10  12  14  16  18  20]
 [  3   6   9  12  15  18  21  24  27  30]
 [  4   8  12  16  20  24  28  32  36  40]
 [  5  10  15  20  25  30  35  40  45  50]
 [  6  12  18  24  30  36  42  48  54  60]
 [  7  14  21  28  35  42  49  56  63  70]
 [  8  16  24  32  40  48  56  64  72  80]
 [  9  18  27  36  45  54  63  72  81  90]
 [ 10  20  30  40  50  60  70  80  90 100]]


Создайте функцию, которая принимает как аргументы целое число N и первый элемент (вещественное число), и разность (вещественное число) и создает матрицу numpy по диагонали, которой располагаются первые N членов арифметической прогрессии.

In [ ]:
def create_matrix(N, first, diff):
    return np.diag(np.arange(first, first + N * diff, diff))
print(create_matrix(5, 2, 2))

[[ 2  0  0  0  0]
 [ 0  4  0  0  0]
 [ 0  0  6  0  0]
 [ 0  0  0  8  0]
 [ 0  0  0  0 10]]


Сгенерируйте средствами numpy матрицу А 5 на 5, содержащую последовательные числа от 1 до 25. Используя срезы извлеките в плоский массив все нечетные элементы этой матрицы.

In [ ]:
a = np.arange(1, 26).reshape(5, 5)
b = a[a%2==1]
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25])

Создайте двумерный массив, содержащий единицы на границе и нули внутри.

In [ ]:
n = 4
a = np.zeros((1,n*n)).reshape(n, n)
np.pad(a, pad_width=1, constant_values=1)

array([[1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1.]])

Создайте две матрицы размером (5,5). Одна матрица содержит 5 в шахматном порядке как в задаче домашнего задания, другая имеет треугольную форму содержащую 5 на основной диагонали и в позициях выше ее, а ниже все 0. Посчитайте их детерминант и найдите обратные матрицы.

In [ ]:
a = np.zeros((5, 5), dtype=int)
a[::2, ::2] = 5
a[1::2, 1::2] = 5
print(np.linalg.det(a))
# singular matrix
# print(np.linalg.inv(a))

b = np.tri(5, dtype=int) * 5
b= np.flip(b)
print(np.linalg.det(b))
print(np.linalg.inv(b))

0.0
3124.999999999999
[[ 0.2 -0.2  0.   0.   0. ]
 [ 0.   0.2 -0.2  0.   0. ]
 [ 0.   0.   0.2 -0.2  0. ]
 [ 0.   0.   0.   0.2 -0.2]
 [ 0.   0.   0.   0.   0.2]]


С помощью pandas загрузите датасет для предсказания цены квартиры, прилагающийся к этой работе.

In [ ]:
import pandas as pd

data = pd.read_csv("data.csv")

FileNotFoundError: ignored

Выведите на экран несколько первых и несколько последний строк файла.

In [ ]:
data.head(3)

Id  DistrictId  Rooms      Square  LifeSquare  KitchenSquare  Floor  \
0  11809          27    3.0  115.027311         NaN           10.0      4   
1   3013          22    1.0   39.832524   23.169223            8.0      7   
2   8215           1    3.0   78.342215   47.671972           10.0      2   

   HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  Social_2  \
0        10.0       2014   0.075424         B         B        11      3097   
1         8.0       1966   0.118537         B         B        30      6207   
2        17.0       1988   0.025609         B         B        33      5261   

   Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2          Price  
0         0           NaN            0        0       B  305018.871089  
1         1        1183.0            1        0       B  177734.553407  
2         0         240.0            3        1       B  282078.720850

In [ ]:
data.tail(3)

Id  DistrictId  Rooms     Square  LifeSquare  KitchenSquare  Floor  \
9997   2795         178    1.0  29.648057   16.555363            5.0      3   
9998  14561          21    1.0  32.330292   22.326870            5.0      3   
9999   7202          94    1.0  35.815476   22.301367            6.0      9   

      HouseFloor  HouseYear  Ecology_1 Ecology_2 Ecology_3  Social_1  \
9997         5.0       1958   0.460556         B         B        20   
9998         9.0       1969   0.194489         B         B        47   
9999         9.0       1975   0.127376         B         B        43   

      Social_2  Social_3  Healthcare_1  Helthcare_2  Shops_1 Shops_2  \
9997      4386        14           NaN            1        5       B   
9998      8004         3         125.0            3        5       B   
9999      8429         3           NaN            3        9       B   

              Price  
9997  165953.912580  
9998  171842.411855  
9999  177685.627486

Выведите с помощью методов pandas основные количественные параметры датасета: количество строк и столбцов, тип данных каждого поля, количество значений в каждом столбце, шкала измерения каждого численного поля.

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 20 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             10000 non-null  int64  
 1   DistrictId     10000 non-null  int64  
 2   Rooms          10000 non-null  float64
 3   Square         10000 non-null  float64
 4   LifeSquare     7887 non-null   float64
 5   KitchenSquare  10000 non-null  float64
 6   Floor          10000 non-null  int64  
 7   HouseFloor     10000 non-null  float64
 8   HouseYear      10000 non-null  int64  
 9   Ecology_1      10000 non-null  float64
 10  Ecology_2      10000 non-null  object 
 11  Ecology_3      10000 non-null  object 
 12  Social_1       10000 non-null  int64  
 13  Social_2       10000 non-null  int64  
 14  Social_3       10000 non-null  int64  
 15  Healthcare_1   5202 non-null   float64
 16  Helthcare_2    10000 non-null  int64  
 17  Shops_1        10000 non-null  int64  
 18  Shops_2

Удалите из таблицы столбцы, содержащие идентификаторы, переименуйте все оставшиеся названия колонок на русском языке.

In [ ]:
data.drop(columns=["DistrictId"], inplace=True)

In [ ]:
data.columns = ["Id", "Комнаты", "Площадь", "ЖилаяПлощадь","ПлощадьКухни", "Этаж", "Этаж2", "Год", "Экология_1", "Экология_2", "Экология_3", "Общество_1", "Общество_2", "Общество_3", "Здоровье_1", "Здоровье_2", "Магазины_1", "Магазины_2", "Цена"]
data

Id  Комнаты     Площадь  ЖилаяПлощадь  ПлощадьКухни  Этаж  Этаж2  \
0     11809      3.0  115.027311           NaN          10.0     4   10.0   
1      3013      1.0   39.832524     23.169223           8.0     7    8.0   
2      8215      3.0   78.342215     47.671972          10.0     2   17.0   
3      2352      1.0   40.409907           NaN           1.0    10   22.0   
4     13866      2.0   64.285067     38.562517           9.0    16   16.0   
...     ...      ...         ...           ...           ...   ...    ...   
9995   1260      2.0   49.090728     33.272626           6.0     3   12.0   
9996  16265      2.0   64.307684     37.038420           9.0    13    0.0   
9997   2795      1.0   29.648057     16.555363           5.0     3    5.0   
9998  14561      1.0   32.330292     22.326870           5.0     3    9.0   
9999   7202      1.0   35.815476     22.301367           6.0     9    9.0   

       Год  Экология_1 Экология_2 Экология_3  Общество_1  Общество_2  \
0     2014    0.075424          B          B          11        3097   
1     1966    0.118537          B          B          30        6207   
2     1988    0.025609          B          B          33        5261   
3     1977    0.007122          B          B           1         264   
4     1972    0.282798          B          B          33        8667   
...    ...         ...        ...        ...         ...         ...   
9995  1981    0.300323          B          B          52       10311   
9996  1977    0.072158          B          B           2         629   
9997  1958    0.460556          B          B          20        4386   
9998  1969    0.194489          B          B          47        8004   
9999  1975    0.127376          B          B          43        8429   

      Общество_3  Здоровье_1  Здоровье_2  Магазины_1 Магазины_2           Цена  
0              0         NaN           0           0          B  305018.871089  
1              1      1183.0           1           0          B  177734.553407  
2              0       240.0           3           1          B  282078.720850  
3              0         NaN           0           1          B  168106.007630  
4              2         NaN           0           6          B  343995.102962  
...          ...         ...         ...         ...        ...            ...  
9995           6         NaN           1           9          B  119367.455796  
9996           1         NaN           0           0          A  199715.148807  
9997          14         NaN           1           5          B  165953.912580  
9998           3       125.0           3           5          B  171842.411855  
9999           3         NaN           3           9          B  177685.627486  

[10000 rows x 19 columns]

Выведите отдельно столбец, содержащий цену, по номеру и названию. Выведите первую, десятую и предпоследнюю строку таблицы по номеру и по индексу.

In [ ]:
data["Цена"]

0       305018.871089
1       177734.553407
2       282078.720850
3       168106.007630
4       343995.102962
            ...      
9995    119367.455796
9996    199715.148807
9997    165953.912580
9998    171842.411855
9999    177685.627486
Name: Цена, Length: 10000, dtype: float64

In [ ]:
data.iloc[[0,10,-2]]

Id  Комнаты     Площадь  ЖилаяПлощадь  ПлощадьКухни  Этаж  Этаж2  \
0     11809      3.0  115.027311           NaN          10.0     4   10.0   
10      535      3.0   74.199049     44.735889          10.0     5   14.0   
9998  14561      1.0   32.330292     22.326870           5.0     3    9.0   

       Год  Экология_1 Экология_2 Экология_3  Общество_1  Общество_2  \
0     2014    0.075424          B          B          11        3097   
10    2008    0.035145          B          B          42        9292   
9998  1969    0.194489          B          B          47        8004   

      Общество_3  Здоровье_1  Здоровье_2  Магазины_1 Магазины_2           Цена  
0              0         NaN           0           0          B  305018.871089  
10             3      2620.0           0           3          B  512797.373401  
9998           3       125.0           3           5          B  171842.411855

In [ ]:
data.sort_values("Id").iloc[[0,10,-2]]

Id  Комнаты     Площадь  ЖилаяПлощадь  ПлощадьКухни  Этаж  Этаж2  \
312       0      1.0  109.144492     84.613939          15.0     6   15.0   
9522     20      1.0   41.132439     24.216388          10.0    24   25.0   
2415  16797      3.0   77.325275     48.101669          10.0     7   16.0   

       Год  Экология_1 Экология_2 Экология_3  Общество_1  Общество_2  \
312   2011    0.319809          B          B          25        4756   
9522  2016    0.243205          B          B           5        1564   
2415  1982    0.282798          B          B          33        8667   

      Общество_3  Здоровье_1  Здоровье_2  Магазины_1 Магазины_2           Цена  
312           16      2857.0           5           8          B  289034.391871  
9522           0       540.0           0           0          B  135481.816381  
2415           2         NaN           0           6          B  354690.491271

Выделите в отдельную таблицу последние десять строк. Уберите в ней столбец с ценой. Склейте ее с первоначальной таблицей при помощи append. Заполните отсутствующие значения цены средним по таблице.

In [ ]:
newData = data.tail(10).copy()
newData["Цена"] = np.ones(10) * data["Цена"].mean()
newData.index = newData.index.map(lambda x: x+10)
pd.concat([data, newData])

Id  Комнаты     Площадь  ЖилаяПлощадь  ПлощадьКухни  Этаж  Этаж2  \
0      11809      3.0  115.027311           NaN          10.0     4   10.0   
1       3013      1.0   39.832524     23.169223           8.0     7    8.0   
2       8215      3.0   78.342215     47.671972          10.0     2   17.0   
3       2352      1.0   40.409907           NaN           1.0    10   22.0   
4      13866      2.0   64.285067     38.562517           9.0    16   16.0   
...      ...      ...         ...           ...           ...   ...    ...   
10005   1260      2.0   49.090728     33.272626           6.0     3   12.0   
10006  16265      2.0   64.307684     37.038420           9.0    13    0.0   
10007   2795      1.0   29.648057     16.555363           5.0     3    5.0   
10008  14561      1.0   32.330292     22.326870           5.0     3    9.0   
10009   7202      1.0   35.815476     22.301367           6.0     9    9.0   

        Год  Экология_1 Экология_2 Экология_3  Общество_1  Общество_2  \
0      2014    0.075424          B          B          11        3097   
1      1966    0.118537          B          B          30        6207   
2      1988    0.025609          B          B          33        5261   
3      1977    0.007122          B          B           1         264   
4      1972    0.282798          B          B          33        8667   
...     ...         ...        ...        ...         ...         ...   
10005  1981    0.300323          B          B          52       10311   
10006  1977    0.072158          B          B           2         629   
10007  1958    0.460556          B          B          20        4386   
10008  1969    0.194489          B          B          47        8004   
10009  1975    0.127376          B          B          43        8429   

       Общество_3  Здоровье_1  Здоровье_2  Магазины_1 Магазины_2  \
0               0         NaN           0           0          B   
1               1      1183.0           1           0          B   
2               0       240.0           3           1          B   
3               0         NaN           0           1          B   
4               2         NaN           0           6          B   
...           ...         ...         ...         ...        ...   
10005           6         NaN           1           9          B   
10006           1         NaN           0           0          A   
10007          14         NaN           1           5          B   
10008           3       125.0           3           5          B   
10009           3         NaN           3           9          B   

                Цена  
0      305018.871089  
1      177734.553407  
2      282078.720850  
3      168106.007630  
4      343995.102962  
...              ...  
10005  214138.857399  
10006  214138.857399  
10007  214138.857399  
10008  214138.857399  
10009  214138.857399  

[10010 rows x 19 columns]

Выделите пять последних колонок в отдельную таблицу. Удалите в ней строки, в которых цена ниже среднего. Присоедините эту таблицу к изначальной (выберите самый подходящий тип соединения).

In [ ]:
newData = data[data.columns[-5:]]
newData = newData[newData["Цена"] >= newData["Цена"].mean()]
pd.concat([data, newData])

Id  Комнаты     Площадь  ЖилаяПлощадь  ПлощадьКухни  Этаж  Этаж2  \
0     11809.0      3.0  115.027311           NaN          10.0   4.0   10.0   
1      3013.0      1.0   39.832524     23.169223           8.0   7.0    8.0   
2      8215.0      3.0   78.342215     47.671972          10.0   2.0   17.0   
3      2352.0      1.0   40.409907           NaN           1.0  10.0   22.0   
4     13866.0      2.0   64.285067     38.562517           9.0  16.0   16.0   
...       ...      ...         ...           ...           ...   ...    ...   
9971      NaN      NaN         NaN           NaN           NaN   NaN    NaN   
9973      NaN      NaN         NaN           NaN           NaN   NaN    NaN   
9977      NaN      NaN         NaN           NaN           NaN   NaN    NaN   
9989      NaN      NaN         NaN           NaN           NaN   NaN    NaN   
9993      NaN      NaN         NaN           NaN           NaN   NaN    NaN   

         Год  Экология_1 Экология_2 Экология_3  Общество_1  Общество_2  \
0     2014.0    0.075424          B          B        11.0      3097.0   
1     1966.0    0.118537          B          B        30.0      6207.0   
2     1988.0    0.025609          B          B        33.0      5261.0   
3     1977.0    0.007122          B          B         1.0       264.0   
4     1972.0    0.282798          B          B        33.0      8667.0   
...      ...         ...        ...        ...         ...         ...   
9971     NaN         NaN        NaN        NaN         NaN         NaN   
9973     NaN         NaN        NaN        NaN         NaN         NaN   
9977     NaN         NaN        NaN        NaN         NaN         NaN   
9989     NaN         NaN        NaN        NaN         NaN         NaN   
9993     NaN         NaN        NaN        NaN         NaN         NaN   

      Общество_3  Здоровье_1  Здоровье_2  Магазины_1 Магазины_2           Цена  
0            0.0         NaN           0           0          B  305018.871089  
1            1.0      1183.0           1           0          B  177734.553407  
2            0.0       240.0           3           1          B  282078.720850  
3            0.0         NaN           0           1          B  168106.007630  
4            2.0         NaN           0           6          B  343995.102962  
...          ...         ...         ...         ...        ...            ...  
9971         NaN         NaN           0           1          B  500562.663412  
9973         NaN         NaN           1           3          B  260456.004692  
9977         NaN         NaN           1           0          B  381850.701985  
9989         NaN       145.0           0           1          B  227361.501595  
9993         NaN         NaN           0           1          B  264213.558631  

[13825 rows x 19 columns]

Выведите таблицу, содержащую среднюю цену и количество квартир на каждом этаже из первоначального набора данных.

In [ ]:
newData = data.groupby("Этаж").agg({'Цена': 'mean', 'Комнаты': 'sum'})

Сохраните получившуюся таблицу в файлы формата csv и xlsx. Прочитайте их и убедитесь, что данные отображаются корректно.

In [ ]:
data.to_csv("floorData.csv")
pd.read_csv("floorData.csv", index_col=0)

Id  Комнаты     Площадь  ЖилаяПлощадь  ПлощадьКухни  Этаж  Этаж2  \
0     11809      3.0  115.027311           NaN          10.0     4   10.0   
1      3013      1.0   39.832524     23.169223           8.0     7    8.0   
2      8215      3.0   78.342215     47.671972          10.0     2   17.0   
3      2352      1.0   40.409907           NaN           1.0    10   22.0   
4     13866      2.0   64.285067     38.562517           9.0    16   16.0   
...     ...      ...         ...           ...           ...   ...    ...   
9995   1260      2.0   49.090728     33.272626           6.0     3   12.0   
9996  16265      2.0   64.307684     37.038420           9.0    13    0.0   
9997   2795      1.0   29.648057     16.555363           5.0     3    5.0   
9998  14561      1.0   32.330292     22.326870           5.0     3    9.0   
9999   7202      1.0   35.815476     22.301367           6.0     9    9.0   

       Год  Экология_1 Экология_2 Экология_3  Общество_1  Общество_2  \
0     2014    0.075424          B          B          11        3097   
1     1966    0.118537          B          B          30        6207   
2     1988    0.025609          B          B          33        5261   
3     1977    0.007122          B          B           1         264   
4     1972    0.282798          B          B          33        8667   
...    ...         ...        ...        ...         ...         ...   
9995  1981    0.300323          B          B          52       10311   
9996  1977    0.072158          B          B           2         629   
9997  1958    0.460556          B          B          20        4386   
9998  1969    0.194489          B          B          47        8004   
9999  1975    0.127376          B          B          43        8429   

      Общество_3  Здоровье_1  Здоровье_2  Магазины_1 Магазины_2           Цена  
0              0         NaN           0           0          B  305018.871089  
1              1      1183.0           1           0          B  177734.553407  
2              0       240.0           3           1          B  282078.720850  
3              0         NaN           0           1          B  168106.007630  
4              2         NaN           0           6          B  343995.102962  
...          ...         ...         ...         ...        ...            ...  
9995           6         NaN           1           9          B  119367.455796  
9996           1         NaN           0           0          A  199715.148807  
9997          14         NaN           1           5          B  165953.912580  
9998           3       125.0           3           5          B  171842.411855  
9999           3         NaN           3           9          B  177685.627486  

[10000 rows x 19 columns]

In [ ]:
data.to_excel("floorData.xlsx")
pd.read_excel('floorData.xlsx', index_col=0)

Id  Комнаты     Площадь  ЖилаяПлощадь  ПлощадьКухни  Этаж  Этаж2  \
0     11809        3  115.027311           NaN            10     4     10   
1      3013        1   39.832524     23.169223             8     7      8   
2      8215        3   78.342215     47.671972            10     2     17   
3      2352        1   40.409907           NaN             1    10     22   
4     13866        2   64.285067     38.562517             9    16     16   
...     ...      ...         ...           ...           ...   ...    ...   
9995   1260        2   49.090728     33.272626             6     3     12   
9996  16265        2   64.307684     37.038420             9    13      0   
9997   2795        1   29.648057     16.555363             5     3      5   
9998  14561        1   32.330292     22.326870             5     3      9   
9999   7202        1   35.815476     22.301367             6     9      9   

       Год  Экология_1 Экология_2 Экология_3  Общество_1  Общество_2  \
0     2014    0.075424          B          B          11        3097   
1     1966    0.118537          B          B          30        6207   
2     1988    0.025609          B          B          33        5261   
3     1977    0.007122          B          B           1         264   
4     1972    0.282798          B          B          33        8667   
...    ...         ...        ...        ...         ...         ...   
9995  1981    0.300323          B          B          52       10311   
9996  1977    0.072158          B          B           2         629   
9997  1958    0.460556          B          B          20        4386   
9998  1969    0.194489          B          B          47        8004   
9999  1975    0.127376          B          B          43        8429   

      Общество_3  Здоровье_1  Здоровье_2  Магазины_1 Магазины_2           Цена  
0              0         NaN           0           0          B  305018.871089  
1              1      1183.0           1           0          B  177734.553407  
2              0       240.0           3           1          B  282078.720850  
3              0         NaN           0           1          B  168106.007630  
4              2         NaN           0           6          B  343995.102962  
...          ...         ...         ...         ...        ...            ...  
9995           6         NaN           1           9          B  119367.455796  
9996           1         NaN           0           0          A  199715.148807  
9997          14         NaN           1           5          B  165953.912580  
9998           3       125.0           3           5          B  171842.411855  
9999           3         NaN           3           9          B  177685.627486  

[10000 rows x 19 columns]

Создайте в Excel или другом табличном редакторе таблицу, содержащую несколько численных и текстовых полей. Прочитайте ее в программу при помощи pandas.

In [ ]:
pd.read_excel("someData.xlsx")

qwe  1  0.01
0  qew  2  0.02
1  weq  3  0.03
2  ewq  4  0.04