# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Лабораторная работа №1.1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [1]:
import numpy as np
a = np.loadtxt("minutes_n_ingredients.csv", dtype= np.int32, delimiter=",", skiprows = 1)
print(a[:5, :])

[[127244     60     16]
 [ 23891     25      7]
 [ 94746     10      6]
 [ 67660      5      6]
 [157911     60     14]]


2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [2]:
a2 = a[:,1:]
print("Минимум")
print(a2.min(axis=0))
print("Максимум")
print(a2.max(axis=0))
print("Среднее значение")
print(np.average(a2, axis=0))
print("Медиана")
print(np.median(a2, axis=0))


Минимум
[0 1]
Максимум
[2147483647         39]
Среднее значение
[2.16010017e+04 9.05528000e+00]
Медиана
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [3]:
b = a[:,1].copy()
np.clip(b, b.min(), np.quantile(b, 0.75))

array([60., 25., 10., ..., 65.,  5., 65.])

4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [4]:
c = np.sum(b==0)
print(c)
a[b==0]=1

479


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [5]:
a5 = np.unique(a[:,1])
np.size(a5)

655

6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [6]:
a6 = np.unique(a[:,-1])
print(np.size(a6))
print(a6)

37
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 37 39]


## Лабораторная работа №1.2

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [7]:
a[a[:, -1]<=5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [8]:
a8 = a[:,2]/a[:,1]
print(a8)
print(a8.max())

[0.26666667 0.28       0.6        ... 0.23076923 0.8        0.1       ]
23.0


9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [9]:
a9 = np.sort(a[:,1])
a[a[:,1]==a9,2][:100].mean()


5.05

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [10]:
np.random.shuffle(a)
print(a[:10])

[[310519     55     10]
 [ 25455    105     10]
 [117844    180     11]
 [204306     20      6]
 [  2781      8     11]
 [463255     30     11]
 [372349    150     18]
 [116782     50     10]
 [342513     30     10]
 [ 63088     60      6]]


11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [11]:
np.size(a[a[:,-1] < np.average(a[:,-1])])/np.size(a)*100

58.989000000000004

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [63]:
a12 = np.logical_and(a[:,1]<=20, a[:,2]<=5)
b12 = np.where(a12, 1 , 0)[np.newaxis,:].T
new_a = np.concatenate((a, b12), axis=1)



13. Выведите процент "простых" рецептов в датасете

In [65]:
np.count_nonzero(new_a[:,3])/100000*100


9.552

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [4]:
np.array([a[np.where(a[:, 1] <= 10)], a[np.where((a[:, 1] > 10) & (a[:, 1] < 20))], a[np.where(a[:, 1] >= 20)]], dtype=object)

array([array([[ 94746,     10,      6],
              [ 67660,      5,      6],
              [366174,      7,      9],
              ...,
              [420725,      5,      3],
              [  4747,      0,      9],
              [370915,      5,      4]]),
       array([[ 33941,     18,      9],
              [446597,     15,      5],
              [ 81006,     12,      7],
              ...,
              [ 44120,     17,      5],
              [ 60756,     15,      5],
              [128811,     15,      4]]),
       array([[127244,     60,     16],
              [ 23891,     25,      7],
              [157911,     60,     14],
              ...,
              [287943,     85,     15],
              [498432,     65,     15],
              [ 81993,    140,     14]])], dtype=object)